
export const cars = [
    {
        "id": "L001",
        "user_id": "U101",
        "username": "CarFanatic23",
        "brand": "Honda",
        "model": "Civic",
        "year": 2019,
        "mileage": 45000,
        "price": 18500,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "White",
        "interior_color": "Black",
        "features": ["Backup Camera", "Bluetooth", "Sunroof"],
        "description": "Well-maintained Honda Civic, great for daily commute. Minor wear and tear.",
        "post_date": "2024-06-15T10:30:00Z",
        "status": "approve",
        "views": 150,
        "inquiries": 10
    },
    {
        "id": "L002",
        "user_id": "U102",
        "username": "SpeedDemon",
        "brand": "Ford",
        "model": "Mustang GT",
        "year": 2022,
        "mileage": 12000,
        "price": 38000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Manual",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["Performance Exhaust", "Leather Seats", "Navigation"],
        "description": "Powerful Mustang GT, barely driven. Excellent condition.",
        "post_date": "2024-06-20T14:00:00Z",
        "status": "approve",
        "views": 250,
        "inquiries": 25
    },
    {
        "id": "L003",
        "user_id": "U103",
        "username": "EcoDriver",
        "brand": "Toyota",
        "model": "Prius",
        "year": 2020,
        "mileage": 30000,
        "price": 22000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Hybrid",
        "exterior_color": "Silver",
        "interior_color": "Gray",
        "features": ["Lane Departure Warning", "Adaptive Cruise Control"],
        "description": "Fuel-efficient Prius, perfect for city driving. Low mileage.",
        "post_date": "2024-06-22T09:15:00Z",
        "status": "reject",
        "views": 180,
        "inquiries": 12
    },
    {
        "id": "L004",
        "user_id": "U104",
        "username": "LuxuryLife",
        "brand": "BMW",
        "model": "X5",
        "year": 2021,
        "mileage": 18000,
        "price": 55000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Beige",
        "features": ["Heated Seats", "Panoramic Sunroof", "Premium Sound System"],
        "description": "Luxurious BMW X5, full options. Excellent condition.",
        "post_date": "2024-06-25T11:45:00Z",
        "status": "pending",
        "views": 300,
        "inquiries": 30
    },
    {
        "id": "L005",
        "user_id": "U105",
        "username": "TruckGuy",
        "brand": "Chevrolet",
        "model": "Silverado 1500",
        "year": 2018,
        "mileage": 60000,
        "price": 28000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Blue",
        "interior_color": "Gray",
        "features": ["Towing Package", "Bed Liner", "4x4"],
        "description": "Reliable Silverado, perfect for work or recreation. Well-maintained.",
        "post_date": "2024-06-28T16:00:00Z",
        "status": "pending",
        "views": 200,
        "inquiries": 15
    },
    {
        "id": "L006",
        "user_id": "U106",
        "username": "CityCommuter",
        "brand": "Hyundai",
        "model": "Elantra",
        "year": 2020,
        "mileage": 25000,
        "price": 16000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Gray",
        "interior_color": "Black",
        "features": ["Apple CarPlay", "Android Auto"],
        "description": "Economical and reliable Elantra, great for city driving.",
        "post_date": "2024-07-01T08:00:00Z",
        "status": "approve",
        "views": 120,
        "inquiries": 8
    },
    {
        "id": "L007",
        "user_id": "U107",
        "username": "AdventureSeeker",
        "brand": "Jeep",
        "model": "Wrangler",
        "year": 2021,
        "mileage": 15000,
        "price": 35000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Green",
        "interior_color": "Black",
        "features": ["Removable Hardtop", "Off-road Tires"],
        "description": "Adventure-ready Wrangler, excellent for off-road enthusiasts.",
        "post_date": "2024-07-03T10:00:00Z",
        "status": "reject",
        "views": 280,
        "inquiries": 22
    },
    {
        "id": "L008",
        "user_id": "U108",
        "username": "FamilyRide",
        "brand": "Honda",
        "model": "CR-V",
        "year": 2022,
        "mileage": 10000,
        "price": 29000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["Blind Spot Monitor", "Power Liftgate"],
        "description": "Spacious and reliable CR-V, perfect for families.",
        "post_date": "2024-07-05T13:30:00Z",
        "status": "Active",
        "views": 190,
        "inquiries": 14
    },
    {
        "id": "L009",
        "user_id": "U109",
        "username": "VintageCollector",
        "brand": "Volkswagen",
        "model": "Beetle",
        "year": 1970,
        "mileage": 80000,
        "price": 15000,
        "currency": "USD",
        "condition": "Used - Classic",
        "transmission": "Manual",
        "fuel_type": "Gasoline",
        "exterior_color": "Yellow",
        "interior_color": "Black",
        "features": ["Original Parts", "Restored Interior"],
        "description": "Classic VW Beetle, fully restored and in excellent running condition.",
        "post_date": "2024-07-06T09:00:00Z",
        "status": "Active",
        "views": 400,
        "inquiries": 45
    },
    {
        "id": "L010",
        "user_id": "U110",
        "username": "TechLover",
        "brand": "Tesla",
        "model": "Model 3",
        "year": 2023,
        "mileage": 5000,
        "price": 45000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Blue",
        "interior_color": "White",
        "features": ["Autopilot", "Full Self-Driving Capability (FSD)", "Panoramic Glass Roof"],
        "description": "Nearly new Tesla Model 3, latest software updates. Impeccable condition.",
        "post_date": "2024-07-08T11:00:00Z",
        "status": "Active",
        "views": 350,
        "inquiries": 40
    },
    {
        "id": "L011",
        "user_id": "U101",
        "username": "CarFanatic23",
        "brand": "Nissan",
        "model": "Altima",
        "year": 2017,
        "mileage": 70000,
        "price": 12000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Gray",
        "features": ["Keyless Entry", "Cruise Control"],
        "description": "Reliable daily driver, minor cosmetic blemishes. Price negotiable.",
        "post_date": "2024-07-09T14:00:00Z",
        "status": "Active",
        "views": 90,
        "inquiries": 5
    },
    {
        "id": "L012",
        "user_id": "U102",
        "username": "SpeedDemon",
        "brand": "Porsche",
        "model": "911 Carrera S",
        "year": 2020,
        "mileage": 8000,
        "price": 95000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "PDK",
        "fuel_type": "Gasoline",
        "exterior_color": "Silver",
        "interior_color": "Red",
        "features": ["Sport Chrono Package", "Bose Sound System"],
        "description": "Stunning 911 Carrera S, low miles, meticulously maintained.",
        "post_date": "2024-07-10T09:30:00Z",
        "status": "Active",
        "views": 500,
        "inquiries": 60
    },
    {
        "id": "L013",
        "user_id": "U103",
        "username": "EcoDriver",
        "brand": "Chevrolet",
        "model": "Bolt EV",
        "year": 2021,
        "mileage": 15000,
        "price": 25000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Blue",
        "interior_color": "Black",
        "features": ["Fast Charging", "Heated Steering Wheel"],
        "description": "All-electric Bolt EV, great range and peppy acceleration.",
        "post_date": "2024-07-11T11:00:00Z",
        "status": "Active",
        "views": 210,
        "inquiries": 18
    },
    {
        "id": "L014",
        "user_id": "U104",
        "username": "LuxuryLife",
        "brand": "Mercedes-Benz",
        "model": "S-Class",
        "year": 2022,
        "mileage": 6000,
        "price": 110000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "White",
        "interior_color": "Tan",
        "features": ["Massaging Seats", "Burmester Surround Sound"],
        "description": "Top-tier luxury with every amenity. Like new condition.",
        "post_date": "2024-07-12T16:00:00Z",
        "status": "Active",
        "views": 450,
        "inquiries": 55
    },
    {
        "id": "L015",
        "user_id": "U105",
        "username": "TruckGuy",
        "brand": "Ram",
        "model": "1500",
        "year": 2020,
        "mileage": 40000,
        "price": 32000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["Uconnect Infotainment", "Trailer Brake Control"],
        "description": "Heavy-duty Ram 1500, ready for any job. Well-maintained.",
        "post_date": "2024-07-13T10:00:00Z",
        "status": "Active",
        "views": 230,
        "inquiries": 19
    },
    {
        "id": "L016",
        "user_id": "U106",
        "username": "CityCommuter",
        "brand": "Kia",
        "model": "Forte",
        "year": 2019,
        "mileage": 35000,
        "price": 14000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Silver",
        "interior_color": "Black",
        "features": ["Rearview Camera", "Bluetooth"],
        "description": "Efficient and reliable daily driver. Great on gas.",
        "post_date": "2024-07-14T08:30:00Z",
        "status": "Active",
        "views": 100,
        "inquiries": 6
    },
    {
        "id": "L017",
        "user_id": "U107",
        "username": "AdventureSeeker",
        "brand": "Subaru",
        "model": "Outback",
        "year": 2023,
        "mileage": 8000,
        "price": 33000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Blue",
        "interior_color": "Black",
        "features": ["AWD", "EyeSight Driver Assist"],
        "description": "Newer Outback, perfect for all seasons. Loaded with safety features.",
        "post_date": "2024-07-15T12:00:00Z",
        "status": "Active",
        "views": 290,
        "inquiries": 28
    },
    {
        "id": "L018",
        "user_id": "U108",
        "username": "FamilyRide",
        "brand": "Toyota",
        "model": "Sienna",
        "year": 2021,
        "mileage": 20000,
        "price": 30000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Hybrid",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["Power Sliding Doors", "Rear Entertainment System"],
        "description": "Family-friendly minivan, excellent for road trips. Hybrid efficiency.",
        "post_date": "2024-07-16T15:00:00Z",
        "status": "Active",
        "views": 200,
        "inquiries": 16
    },
    {
        "id": "L019",
        "user_id": "U109",
        "username": "VintageCollector",
        "brand": "Ford",
        "model": "Thunderbird",
        "year": 1965,
        "mileage": 90000,
        "price": 28000,
        "currency": "USD",
        "condition": "Used - Classic",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "White",
        "features": ["Power Windows", "Original Radio"],
        "description": "Iconic '65 Thunderbird, runs and drives beautifully. Head-turner.",
        "post_date": "2024-07-17T09:00:00Z",
        "status": "Active",
        "views": 480,
        "inquiries": 50
    },
    {
        "id": "L020",
        "user_id": "U110",
        "username": "TechLover",
        "brand": "Rivian",
        "model": "R1T",
        "year": 2024,
        "mileage": 2000,
        "price": 78000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Green",
        "interior_color": "Black",
        "features": ["Quad-Motor AWD", "Air Suspension"],
        "description": "Next-gen electric truck, incredibly capable on and off-road. Low mileage.",
        "post_date": "2024-07-18T13:00:00Z",
        "status": "Active",
        "views": 380,
        "inquiries": 42
    },
    {
        "id": "L021",
        "user_id": "U111",
        "username": "BudgetBuyer",
        "brand": "Nissan",
        "model": "Versa",
        "year": 2015,
        "mileage": 85000,
        "price": 8000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Gray",
        "interior_color": "Black",
        "features": ["AC", "Radio"],
        "description": "Economical commuter, reliable and good on gas. Minor dents.",
        "post_date": "2024-07-19T10:00:00Z",
        "status": "Active",
        "views": 70,
        "inquiries": 3
    },
    {
        "id": "L022",
        "user_id": "U112",
        "username": "PerformanceFan",
        "brand": "Audi",
        "model": "RS 5 Sportback",
        "year": 2022,
        "mileage": 7000,
        "price": 72000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Nardo Gray",
        "interior_color": "Black with Red Stitching",
        "features": ["Quattro AWD", "Sport Exhaust"],
        "description": "High-performance Sportback, exhilarating to drive. Pristine condition.",
        "post_date": "2024-07-20T14:30:00Z",
        "status": "Active",
        "views": 320,
        "inquiries": 35
    },
    {
        "id": "L023",
        "user_id": "U113",
        "username": "GreenDriver",
        "brand": "Hyundai",
        "model": "Kona Electric",
        "year": 2023,
        "mileage": 4000,
        "price": 31000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["Heated Seats", "Touchscreen Display"],
        "description": "Compact electric SUV, great for urban environments. Long range.",
        "post_date": "2024-07-21T09:45:00Z",
        "status": "Active",
        "views": 200,
        "inquiries": 15
    },
    {
        "id": "L024",
        "user_id": "U114",
        "username": "ExecutiveDriver",
        "brand": "Lexus",
        "model": "ES 350",
        "year": 2021,
        "mileage": 15000,
        "price": 38000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Silver",
        "interior_color": "Tan",
        "features": ["Mark Levinson Audio", "Heated/Ventilated Seats"],
        "description": "Smooth and luxurious sedan, renowned for reliability. Excellent condition.",
        "post_date": "2024-07-22T11:30:00Z",
        "status": "Active",
        "views": 250,
        "inquiries": 20
    },
    {
        "id": "L025",
        "user_id": "U115",
        "username": "ConstructionPro",
        "brand": "Ford",
        "model": "F-250 Super Duty",
        "year": 2019,
        "mileage": 55000,
        "price": 45000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Diesel",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["Gooseneck Hitch", "Snow Plow Prep"],
        "description": "Heavy-duty truck, perfect for towing and demanding jobs. Diesel power.",
        "post_date": "2024-07-23T16:00:00Z",
        "status": "Active",
        "views": 280,
        "inquiries": 25
    },
    {
        "id": "L026",
        "user_id": "U116",
        "username": "DailyDriver",
        "brand": "Honda",
        "model": "Accord",
        "year": 2018,
        "mileage": 50000,
        "price": 19000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Blue",
        "interior_color": "Black",
        "features": ["Apple CarPlay", "Android Auto"],
        "description": "Reliable and spacious Accord, great for daily commuting.",
        "post_date": "2024-07-24T08:00:00Z",
        "status": "Active",
        "views": 160,
        "inquiries": 10
    },
    {
        "id": "L027",
        "user_id": "U117",
        "username": "OffRoadEnthusiast",
        "brand": "Toyota",
        "model": "4Runner TRD Pro",
        "year": 2020,
        "mileage": 25000,
        "price": 42000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Cement Gray",
        "interior_color": "Black",
        "features": ["TRD Suspension", "Roof Rack"],
        "description": "Capable off-roader, ready for any adventure. Well-equipped.",
        "post_date": "2024-07-25T12:00:00Z",
        "status": "Active",
        "views": 350,
        "inquiries": 30
    },
    {
        "id": "L028",
        "user_id": "U118",
        "username": "SoccerMom",
        "brand": "Chrysler",
        "model": "Pacifica",
        "year": 2022,
        "mileage": 12000,
        "price": 32000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Silver",
        "interior_color": "Black",
        "features": ["Stow 'n Go Seating", "Vacuum Cleaner"],
        "description": "Family minivan with convenient features. Low mileage.",
        "post_date": "2024-07-26T15:30:00Z",
        "status": "Active",
        "views": 180,
        "inquiries": 14
    },
    {
        "id": "L029",
        "user_id": "U119",
        "username": "ClassicCarLover",
        "brand": "Chevrolet",
        "model": "Corvette Stingray",
        "year": 1972,
        "mileage": 65000,
        "price": 40000,
        "currency": "USD",
        "condition": "Used - Classic",
        "transmission": "Manual",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["T-Tops", "Original Engine"],
        "description": "Vintage Stingray, runs strong. A true American muscle car.",
        "post_date": "2024-07-27T09:00:00Z",
        "status": "Active",
        "views": 520,
        "inquiries": 58
    },
    {
        "id": "L030",
        "user_id": "U120",
        "username": "ElectricFuture",
        "brand": "Lucid",
        "model": "Air Grand Touring",
        "year": 2024,
        "mileage": 1000,
        "price": 120000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "White",
        "interior_color": "Tan",
        "features": ["Long Range", "Glass Canopy"],
        "description": "Cutting-edge electric luxury sedan. Practically brand new.",
        "post_date": "2024-07-28T11:00:00Z",
        "status": "Active",
        "views": 400,
        "inquiries": 48
    },
    {
        "id": "L031",
        "user_id": "U101",
        "username": "CarFanatic23",
        "brand": "Subaru",
        "model": "Impreza",
        "year": 2016,
        "mileage": 75000,
        "price": 10000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Silver",
        "interior_color": "Black",
        "features": ["AWD", "Bluetooth"],
        "description": "Reliable AWD sedan, good for all weather conditions. Minor cosmetic wear.",
        "post_date": "2024-07-29T10:30:00Z",
        "status": "Active",
        "views": 85,
        "inquiries": 4
    },
    {
        "id": "L032",
        "user_id": "U102",
        "username": "SpeedDemon",
        "brand": "Mercedes-AMG",
        "model": "GT 63 S",
        "year": 2021,
        "mileage": 6000,
        "price": 130000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Red",
        "features": ["Performance Seats", "Carbon Fiber Trim"],
        "description": "Blistering performance and luxury. Immaculate condition.",
        "post_date": "2024-07-30T14:00:00Z",
        "status": "Active",
        "views": 550,
        "inquiries": 70
    },
    {
        "id": "L033",
        "user_id": "U103",
        "username": "EcoDriver",
        "brand": "Nissan",
        "model": "Leaf",
        "year": 2019,
        "mileage": 28000,
        "price": 17000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["ProPILOT Assist", "e-Pedal"],
        "description": "Affordable EV, perfect for daily commuting. Good range.",
        "post_date": "2024-07-31T09:15:00Z",
        "status": "Active",
        "views": 180,
        "inquiries": 11
    },
    {
        "id": "L034",
        "user_id": "U104",
        "username": "LuxuryLife",
        "brand": "Cadillac",
        "model": "Escalade",
        "year": 2023,
        "mileage": 8000,
        "price": 85000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Brown",
        "features": ["Super Cruise", "AKG Studio Audio"],
        "description": "Ultimate luxury SUV, loaded with technology. Like new.",
        "post_date": "2024-08-01T11:45:00Z",
        "status": "Active",
        "views": 380,
        "inquiries": 45
    },
    {
        "id": "L035",
        "user_id": "U105",
        "username": "TruckGuy",
        "brand": "GMC",
        "model": "Sierra 2500HD",
        "year": 2021,
        "mileage": 30000,
        "price": 50000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Diesel",
        "exterior_color": "Gray",
        "interior_color": "Black",
        "features": ["Duramax Diesel", "ProGrade Trailering System"],
        "description": "Heavy-duty workhorse, powerful and reliable. Ready for big jobs.",
        "post_date": "2024-08-02T16:00:00Z",
        "status": "Active",
        "views": 260,
        "inquiries": 22
    },
    {
        "id": "L036",
        "user_id": "U106",
        "username": "CityCommuter",
        "brand": "Mazda",
        "model": "CX-5",
        "year": 2020,
        "mileage": 22000,
        "price": 21000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["AWD", "Heated Seats"],
        "description": "Stylish and fun-to-drive compact SUV. Excellent condition.",
        "post_date": "2024-08-03T08:00:00Z",
        "status": "Active",
        "views": 170,
        "inquiries": 13
    },
    {
        "id": "L037",
        "user_id": "U107",
        "username": "AdventureSeeker",
        "brand": "Land Rover",
        "model": "Defender 110",
        "year": 2023,
        "mileage": 5000,
        "price": 68000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "White",
        "interior_color": "Black",
        "features": ["Off-Road Capability", "Panoramic Roof"],
        "description": "New-gen Defender, combines ruggedness with luxury. Low miles.",
        "post_date": "2024-08-04T10:00:00Z",
        "status": "Active",
        "views": 330,
        "inquiries": 38
    },
    {
        "id": "L038",
        "user_id": "U108",
        "username": "FamilyRide",
        "brand": "Honda",
        "model": "Odyssey",
        "year": 2020,
        "mileage": 35000,
        "price": 27000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Gray",
        "features": ["HondaVAC", "Rear Entertainment System"],
        "description": "Spacious and feature-packed minivan, perfect for families.",
        "post_date": "2024-08-05T13:30:00Z",
        "status": "Active",
        "views": 195,
        "inquiries": 15
    },
    {
        "id": "L039",
        "user_id": "U109",
        "username": "VintageCollector",
        "brand": "Pontiac",
        "model": "GTO",
        "year": 1968,
        "mileage": 70000,
        "price": 35000,
        "currency": "USD",
        "condition": "Used - Classic",
        "transmission": "Manual",
        "fuel_type": "Gasoline",
        "exterior_color": "Orange",
        "interior_color": "Black",
        "features": ["Original Engine", "Power Steering"],
        "description": "Legendary muscle car, well-preserved. A true collector's item.",
        "post_date": "2024-08-06T09:00:00Z",
        "status": "Active",
        "views": 500,
        "inquiries": 55
    },
    {
        "id": "L040",
        "user_id": "U110",
        "username": "TechLover",
        "brand": "Polestar",
        "model": "2",
        "year": 2022,
        "mileage": 9000,
        "price": 48000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Gray",
        "interior_color": "Black",
        "features": ["Google Android Automotive OS", "Panoramic Glass Roof"],
        "description": "Sleek and performance-oriented EV. Excellent condition.",
        "post_date": "2024-08-07T11:00:00Z",
        "status": "Active",
        "views": 300,
        "inquiries": 35
    },
    {
        "id": "L041",
        "user_id": "U111",
        "username": "BudgetBuyer",
        "brand": "Hyundai",
        "model": "Accent",
        "year": 2017,
        "mileage": 60000,
        "price": 9500,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Gray",
        "features": ["Bluetooth", "USB Port"],
        "description": "Compact and fuel-efficient, ideal for a first car or city driving.",
        "post_date": "2024-08-08T10:00:00Z",
        "status": "Active",
        "views": 95,
        "inquiries": 6
    },
    {
        "id": "L042",
        "user_id": "U112",
        "username": "PerformanceFan",
        "brand": "BMW",
        "model": "M3 Competition",
        "year": 2023,
        "mileage": 3000,
        "price": 80000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Isle of Man Green",
        "interior_color": "Black with Carbon Trim",
        "features": ["M Adaptive Suspension", "Carbon Ceramic Brakes"],
        "description": "Track-ready M3, practically new. Unrivaled driving experience.",
        "post_date": "2024-08-09T14:30:00Z",
        "status": "Active",
        "views": 400,
        "inquiries": 50
    },
    {
        "id": "L043",
        "user_id": "U113",
        "username": "GreenDriver",
        "brand": "Volkswagen",
        "model": "ID.4",
        "year": 2022,
        "mileage": 10000,
        "price": 35000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["Panoramic Fixed Glass Roof", "Travel Assist"],
        "description": "Spacious and comfortable EV SUV. Great for families.",
        "post_date": "2024-08-10T09:45:00Z",
        "status": "Active",
        "views": 230,
        "inquiries": 17
    },
    {
        "id": "L044",
        "user_id": "U114",
        "username": "ExecutiveDriver",
        "brand": "Audi",
        "model": "A6",
        "year": 2020,
        "mileage": 28000,
        "price": 36000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Brown",
        "features": ["Virtual Cockpit", "Premium Plus Package"],
        "description": "Sophisticated executive sedan, comfortable and technologically advanced.",
        "post_date": "2024-08-11T11:30:00Z",
        "status": "Active",
        "views": 260,
        "inquiries": 21
    },
    {
        "id": "L045",
        "user_id": "U115",
        "username": "ConstructionPro",
        "brand": "Chevrolet",
        "model": "Colorado",
        "year": 2018,
        "mileage": 65000,
        "price": 25000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Black",
        "features": ["Z71 Off-Road Package", "Tow/Haul Mode"],
        "description": "Mid-size truck, capable for work and weekend adventures. Well-maintained.",
        "post_date": "2024-08-12T16:00:00Z",
        "status": "Active",
        "views": 200,
        "inquiries": 18
    },
    {
        "id": "L046",
        "user_id": "U116",
        "username": "DailyDriver",
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2019,
        "mileage": 40000,
        "price": 17000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "White",
        "interior_color": "Gray",
        "features": ["Toyota Safety Sense", "Backup Camera"],
        "description": "Extremely reliable and fuel-efficient Corolla. Perfect for daily commute.",
        "post_date": "2024-08-13T08:00:00Z",
        "status": "Active",
        "views": 150,
        "inquiries": 9
    },
    {
        "id": "L047",
        "user_id": "U117",
        "username": "OffRoadEnthusiast",
        "brand": "Ford",
        "model": "Bronco Badlands",
        "year": 2022,
        "mileage": 7000,
        "price": 50000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Area 51",
        "interior_color": "Black",
        "features": ["Sasquatch Package", "Modular Hard Top"],
        "description": "Capable and iconic off-roader. Ready for serious trails.",
        "post_date": "2024-08-14T12:00:00Z",
        "status": "Active",
        "views": 390,
        "inquiries": 40
    },
    {
        "id": "L048",
        "user_id": "U118",
        "username": "SoccerMom",
        "brand": "Honda",
        "model": "Pilot",
        "year": 2021,
        "mileage": 25000,
        "price": 30000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Gasoline",
        "exterior_color": "Black",
        "interior_color": "Gray",
        "features": ["Third-Row Seating", "Honda Sensing"],
        "description": "Spacious and comfortable SUV for the whole family. Excellent condition.",
        "post_date": "2024-08-15T15:30:00Z",
        "status": "Active",
        "views": 210,
        "inquiries": 16
    },
    {
        "id": "L049",
        "user_id": "U119",
        "username": "ClassicCarLover",
        "brand": "Porsche",
        "model": "911 (964)",
        "year": 1990,
        "mileage": 95000,
        "price": 80000,
        "currency": "USD",
        "condition": "Used - Classic",
        "transmission": "Manual",
        "fuel_type": "Gasoline",
        "exterior_color": "Red",
        "interior_color": "Tan",
        "features": ["Air-Cooled Engine", "Original Fuchs Wheels"],
        "description": "Iconic air-cooled 911, a driver's car. Well-preserved.",
        "post_date": "2024-08-16T09:00:00Z",
        "status": "Active",
        "views": 600,
        "inquiries": 65
    },
    {
        "id": "L050",
        "user_id": "U120",
        "username": "ElectricFuture",
        "brand": "Hyundai",
        "model": "IONIQ 5",
        "year": 2024,
        "mileage": 1500,
        "price": 52000,
        "currency": "USD",
        "condition": "Used",
        "transmission": "Automatic",
        "fuel_type": "Electric",
        "exterior_color": "Atlas White",
        "interior_color": "Black",
        "features": ["Ultra-Fast Charging", "Vehicle-to-Load (V2L)"],
        "description": "Futuristic EV with excellent range and unique design. Like new.",
        "post_date": "2024-08-17T11:00:00Z",
        "status": "Active",
        "views": 450,
        "inquiries": 52
    }
]